### ISSUE TITLE
Updates to non-stable versions

### ISSUE THREAD

**Issue by tobtobxx** [MindustryInside/AutoUpdater#1]
AutoUpdater just updated my version to the pre-alpha release v128.
This renders my client incompatible for hosting maps for other players (stable: v126).

It would be very nice, if AutoUpdater only updates to stable releases.

I'll maybe look into the code to fix if I find time...

**Comment by skykatik** [comment]
It's a good idea, and I think I even know how to implement it

**Comment by tobtobxx** [comment]
WOW, cool thanks!!!
