### ISSUE TITLE
Startup crash when running the game with the mod on

### ISSUE THREAD

**Issue by aarrbba123** [MindustryInside/AutoUpdater#2]
[crash-report-08_13_2021_23_48_03.txt](https://github.com/MindustryInside/AutoUpdater/files/6983676/crash-report-08_13_2021_23_48_03.txt)
When the game is restarted,it crashes immediately.
(The only mod enabled is this mod)

**Comment by skykatik** [comment]
Hello, at the moment in releases and in the `main` branch, the mod is compatible only with 6.0.

Try using the mod from the `7.0` branch.

**Comment by skykatik** [comment]
I added CI, try the build from here:
https://github.com/MindustryInside/AutoUpdater/suites/3494480621/artifacts/83219606
